// This file is machine-generated - edit at your own risk!

'use server';

/**
 * @fileOverview AI-powered listing description generator for hosts.
 *
 * - generateListingDescription - Generates a listing description based on provided details and amenities.
 * - GenerateListingDescriptionInput - The input type for the generateListingDescription function.
 * - GenerateListingDescriptionOutput - The return type for the generateListingDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateListingDescriptionInputSchema = z.object({
  propertyType: z.string().describe('Type of property (e.g., house, apartment, condo).'),
  location: z.string().describe('Location of the property (city, neighborhood).'),
  numberOfGuests: z.number().describe('Maximum number of guests the property can accommodate.'),
  numberOfBedrooms: z.number().describe('Number of bedrooms in the property.'),
  numberOfBathrooms: z.number().describe('Number of bathrooms in the property.'),
  amenities: z.array(z.string()).describe('List of amenities available at the property (e.g., WiFi, kitchen, parking).'),
  uniqueFeatures: z.string().describe('Any unique or notable features of the property.'),
});
export type GenerateListingDescriptionInput = z.infer<typeof GenerateListingDescriptionInputSchema>;

const GenerateListingDescriptionOutputSchema = z.object({
  description: z.string().describe('A compelling property listing description generated by AI.'),
});
export type GenerateListingDescriptionOutput = z.infer<typeof GenerateListingDescriptionOutputSchema>;

export async function generateListingDescription(
  input: GenerateListingDescriptionInput
): Promise<GenerateListingDescriptionOutput> {
  return generateListingDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateListingDescriptionPrompt',
  input: {schema: GenerateListingDescriptionInputSchema},
  output: {schema: GenerateListingDescriptionOutputSchema},
  prompt: `You are an expert copywriter specializing in creating attractive property listings.

  Based on the details and amenities provided, generate a compelling and engaging description for the property.
  The description should highlight the key features and benefits of the property to attract potential guests.

  Property Type: {{{propertyType}}}
  Location: {{{location}}}
  Number of Guests: {{{numberOfGuests}}}
  Number of Bedrooms: {{{numberOfBedrooms}}}
  Number of Bathrooms: {{{numberOfBathrooms}}}
  Amenities: {{#each amenities}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  Unique Features: {{{uniqueFeatures}}}
  `,
});

const generateListingDescriptionFlow = ai.defineFlow(
  {
    name: 'generateListingDescriptionFlow',
    inputSchema: GenerateListingDescriptionInputSchema,
    outputSchema: GenerateListingDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
